image: europe-docker.pkg.dev/gardener-project/public/gardener/extensions/registry-cache:latest
imagePullPolicy: IfNotPresent

replicaCount: 1

# settings for metrics, e.g. scraping by seed-prometheus
metrics:
  enableScraping: true
  # default metrics endpoint in controller-runtime
  port: 8080

resources:
  requests:
    # TODO: Revise these values depending on the discussion with Vedran.
    cpu: 50m
    memory: 64Mi
  limits:
    memory: 3Gi
vpa:
  enabled: true
  resourcePolicy:
    controlledValues: RequestsOnly
    minAllowed:
      memory: 32Mi
  updatePolicy:
    updateMode: "Auto"

healthPort: 8081

controllers:
  extension:
    concurrentSyncs: 5
  heartbeat: 
    renewIntervalSeconds: 30 
  ignoreOperationAnnotation: false

webhookConfig:
  servicePort: 443
  serverPort: 10250

disableControllers: []

imageVectorOverwrite: {}
  # images:
  #   - name: registry
  #     sourceRepository: github.com/distribution/distribution
  #     repository: europe-docker.pkg.dev/gardener-project/releases/3rd/registry
  #     tag: "3.0.0-beta.1"

gardener:
  version: ""
